default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hackthebias_development
  username: hackthebias_development_admin
  password: <%= Rails.application.credentials.DB_PASSWORD.dev_db %>

test:
  <<: *default
  database: hackthebias_test