default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hackthebias_development
  username: hackthebias_development_admin
  password: <%= Rails.application.credentials.DB_PASSWORD.dev_db %>

test:
  <<: *default
  database: hackthebias_test

production:
  <<: *default
  database: hackthebias_production
  username: <%= Rails.application.credentials.DB_USER.prod_user %>
  host: <%= Rails.application.credentials.DB_HOST.prod_host %>
  password: <%= Rails.application.credentials.DB_PASSWORD.prod_db %>
